In [1]:
import numpy as np
from sklearn.metrics import confusion_matrix
import os
import matplotlib.pyplot as plt

# seaborn can be used to "prettify" default matplotlib plots by importing and setting as default
import seaborn as sns
sns.set() # Set searborn as default

## Load dataset

In [2]:
dataPath = os.path.join('..','Data', 'FisherIris.csv')
# Dump data file into an array
with open(dataPath, "r") as ins:
    listArray = [line.replace('\n', '').split('\t') for line in ins]
    
attributeNames = []

# Encode data in desired format
n = len(listArray) - 1
p = len(listArray[0][0].split(',')) - 1
X = np.zeros((n, p))
y = np.zeros(n)
for i, data in enumerate(listArray):
    dataTemp = data[0].split(',')
    if i == 0: # first row is attribute names
        attributeNames = dataTemp[0:4]
    else:
        X[i - 1,:] = dataTemp[0:4]
        flowerInd = dataTemp[4]
        if flowerInd == 'Setosa':
            y[i-1] = 0
        elif flowerInd == "Versicolor":
            y[i-1] = 1
        else:
            y[i-1] = 2

> Calculate plug-in estimates of $\hat{\pi}_k$, $\hat{\mu}_k$, and $\hat{\Sigma}$

In [3]:
pi = np.zeros(3)
mu = np.zeros((3, p))
S = np.zeros((p,p))



print(pi)
print(mu)
print(S)

[0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


> Calculate discriminant function $\delta_k$

In [4]:
def produceDiscriminantLine(X, S, mu, pi):
    
    
    return

# Discriminants
d = np.zeros((3, n))
for i in range(3):
    d[i,:] = produceDiscriminantLine(X, S, mu[i,:], pi[i])

> Predict class belongings for all observations in training data

In [5]:
# Classify according to discriminant
yhat = 

SyntaxError: invalid syntax (1496561819.py, line 2)

> Calculate the confusion matrix for training data

In [ ]:
# If you run version 0.22 or higher of sklearn then you can plot the confusion matrix.
# Plot non-normalized confusion matrix
from sklearn.metrics import ConfusionMatrixDisplay

disp = 

# NOTE: Fill all variables here with default values of the plot_confusion_matrix
disp = disp.plot(include_values=True, cmap='Blues', ax=None)
plt.grid(None)
plt.show()